
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 686463394123-pbb4dfjo1q7qcv8ht3j6mtg567q7u03u.apps.googleusercontent.com
            client-secret: nbMFikimxqWNpFQOPuhxvCIG
            scope: profile,email